apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  MASTER_KEY: "postgres"
  AUTH_DB_URL: "postgresql://postgres:postgres@auth-db.cijy6u8o0pso.us-east-1.rds.amazonaws.com:5432/auth"
  FLAG_DB_URL: "postgresql://postgres:postgres@flag-db.cijy6u8o0pso.us-east-1.rds.amazonaws.com:5432/flags"
  TARGETING_DB_URL: "postgresql://postgres:postgres@targeting-db.cijy6u8o0pso.us-east-1.rds.amazonaws.com:5432/targeting"
  REDIS_URL: "rediss://togglemaster-redis-0001-001.togglemaster-redis.77i2t1.use1.cache.amazonaws.com:6379"
  SQS_URL: "https://sqs.us-east-1.amazonaws.com/288302021178/analytics-events-queue"
  AWS_REGION: "us-east-1"
  DYNAMODB_TABLE: "ToggleMasterAnalytics"