apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
type: Opaque
stringData:
  # Flag Service
  FLAG_DB_URL: "postgresql://postgres:ToggleMaster2024!@togglemaster-flag.c3esyscigqw9.us-east-2.rds.amazonaws.com:5432/flagdb?sslmode=require"

  # Auth Service
  AUTH_DB_URL: "postgresql://postgres:ToggleMaster2024!@togglemaster-auth.c3esyscigqw9.us-east-2.rds.amazonaws.com:5432/authdb?sslmode=require"
  MASTER_KEY: "ToggleMaster2024!"

  # Targeting Service
  TARGETING_DB_URL: "postgresql://postgres:ToggleMaster2024!@togglemaster-flag.c3esyscigqw9.us-east-2.rds.amazonaws.com:5432/targetingdb?sslmode=require"
  TARGETING_DB_PASSWORD: "ToggleMaster2024!"

  # Shared infrastructure
  REDIS_URL: "redis://togglemaster-redis.mulz1c.0001.use2.cache.amazonaws.com:6379"
  SQS_URL: "https://sqs.us-east-2.amazonaws.com/012438021718/togglemaster-events"
